# Generated by Django 4.1.3 on 2022-12-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_type', models.CharField(choices=[('groupe', 'Groupe'), ('private_chat', 'Private Chat')], default='private_chat', max_length=20, verbose_name='chat type')),
                ('members', models.ManyToManyField(related_name='chats', to='accounts.projectuser', verbose_name='members')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='accounts.project', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('message_file', models.FileField(upload_to='messages/', verbose_name='file')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='chat')),
                ('replied_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.projectuser', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
