# Generated by Django 4.1.3 on 2023-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='accounts.projectuser', verbose_name='viewed users'),
        ),
    ]
