# Generated by Django 4.1.3 on 2023-01-31 17:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='text')),
        ),
    ]
