# Generated by Django 4.1.3 on 2023-01-31 21:33

import chat.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='key',
            field=models.CharField(blank=True, default=chat.utils.generate_chat_key, max_length=21, null=True),
        ),
    ]
