# Generated by Django 4.1.3 on 2023-01-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='identifier',
            field=models.CharField(default=1, max_length=255, verbose_name='identifier'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expire_on', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
