# Generated by Django 4.1.3 on 2023-01-16 17:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_apptoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptoken',
            name='key',
            field=models.CharField(blank=True, default=accounts.models.generate_key, max_length=256, primary_key=True, serialize=False),
        ),
    ]
