# Generated by Django 4.1.3 on 2023-01-16 17:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_apptoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptoken',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apptoken',
            name='key',
            field=models.CharField(blank=True, default=accounts.models.generate_key, max_length=256, null=True),
        ),
    ]
