# Generated by Django 4.1.3 on 2023-01-27 12:30

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_apptoken_id_alter_apptoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptoken',
            name='key',
            field=models.CharField(blank=True, default=accounts.utils.generate_key, max_length=256, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.UniqueConstraint(fields=('project', 'identifier'), name='unique_project_user'),
        ),
    ]
