# Generated by Django 4.1.3 on 2023-01-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_apptoken_key_projectuser_unique_project_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_project'),
        ),
    ]
